// Generated by Wrangler on Mon Jul 22 2024 06:14:18 GMT+0545 (Nepal Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	cache: KVNamespace;
	UPSTASH_REDIS_REST_URL: "https://clever-magpie-34989.upstash.io";
	UPSTASH_REDIS_REST_TOKEN: "AYitAAIncDE5MjEwYTk4YTM3ZDc0OWIwYjQ1NTgyODdlYmU0NmIyY3AxMzQ5ODk";
	UPSTASH_KAFKA_REST_PASSWORD: "MjZlNTExY2UtNDFkNy00M2I0LTlmMzQtZjRmNjBhN2ZlYjM4";
	UPSTASH_KAFKA_REST_URL: "precious-mastodon-5433-us1-kafka.upstash.io:9092";
	UPSTASH_KAFKA_REST_USERNAME: "cHJlY2lvdXMtbWFzdG9kb24tNTQzMyRazNl64ovZv_6NZAu-73hr6PgNHO6V370";
	COOKIE_SESSION_SECRET: "secret";
	GITHUB_CLIENT_ID: "Ov23liQlTaXkAND0Xd8I";
	GITHUB_CLIENT_SECRET: "a3be63c1a5b5809afa0899d88eb4ec8fd6feab97";
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_DATABASE_ID: string;
	CLOUDFLARE_D1_TOKEN: string;
	ACC_TOKEN: string;
	DB: D1Database;
	MY_INDEX: VectorizeIndex;
	AI: Ai;
}
