// Generated by Wrangler on Mon Jul 22 2024 06:34:49 GMT+0545 (Nepal Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	cache: KVNamespace;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_DATABASE_ID: string;
	CLOUDFLARE_D1_TOKEN: string;
	ACC_TOKEN: string;
	VECTORURL: string;
	UPSTASH_REDIS_REST_URL: string;
	UPSTASH_REDIS_REST_TOKEN: string;
	UPSTASH_KAFKA_REST_PASSWORD: string;
	UPSTASH_KAFKA_REST_URL: string;
	UPSTASH_KAFKA_REST_USERNAME: string;
	COOKIE_SESSION_SECRET: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	PINE_CONE_API_KEY: string;
	DB: D1Database;
	AI: Ai;
}
